import React from 'react';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Candidate",
  description: "Generated by create next app",
};

export default function CandidateLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <div className='flex flex-col h-screen'>{children}</div>
}