import React from 'react';
import type { Metadata } from "next";
import { ModalProvider } from '@/context/CreateJobModalContext';
import { BreadCrumbProvider } from '@/context/BreadCrumbContext';
import { ProfileInformationProvider } from '@/context/ProfileInformationContext';
import CreateJobModal from "@/components/modals/CreateJobModal";
import Navbar2 from "@/components/Navbar2";

export const metadata: Metadata = {
  title: "Candidate",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: {
        children: React.ReactNode
    }) {
        return (
            <ModalProvider>
                <BreadCrumbProvider>
                    <ProfileInformationProvider>
                        <div className='flex flex-col h-screen'>
                            <main className="flex flex-col h-screen">
                                <CreateJobModal/>
                                <Navbar2/>
                                {children}
                            </main>
                        </div>
                    </ProfileInformationProvider>
                </BreadCrumbProvider>
            </ModalProvider>
        )
    }