import React from 'react';
import type { Metadata } from "next";
import { ModalProvider } from '@/context/CreateJobModalContext';
import { BreadCrumbProvider } from '@/context/BreadCrumbContext';

export const metadata: Metadata = {
  title: "Candidate",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }: {
        children: React.ReactNode
    }) {
        return (
            <ModalProvider>
                <BreadCrumbProvider>
                    <div className='flex flex-col h-screen'>{children}</div>
                </BreadCrumbProvider>
            </ModalProvider>
        )
    }